import { randomUUID } from 'node:crypto';
import { ErrorCode } from '../utils/response.js';

const CAPTCHA_TTL_MS = 5 * 60 * 1000;

const CAPTCHA_PATH_SIGNATURES: Record<string, string> = {
  A: 'MLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQZMLLLQLLQLLQLLQLLQLLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLLQZ',
  B: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQZMLLQLLQLLQLLQLLLQLLQLLQLLQZMLLLQLLLLLQLLLQLLQLLQLLQLLQLLQZ',
  C: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  D: 'MLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQZ',
  E: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  F: 'MLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQZ',
  G: 'MLLQLLQLLQLLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQZMLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLZ',
  H: 'MLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  J: 'MLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  K: 'MLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLLLLQZMLLQLLQLLQLLLQLLQLLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  L: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  M: 'MLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQZ',
  N: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLZMLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  O: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQZ',
  P: 'MLLQLLQLLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLLQZ',
  Q: 'MLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLLQLLLQLLQLLQLLQLLQZMLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLLLLQLLQLLQZ',
  R: 'MLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLLQLLQLLQZMLLLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQZMLLQLLLQLLQLLQLLQLLQLLQLLQZ',
  S: 'MLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLLQLLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  T: 'MLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  U: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  V: 'MLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  W: 'MLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLLQLLQLLQLLQLLQLLQLLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQZ',
  X: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQZ',
  Y: 'MLLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLZ',
  Z: 'MLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLLQLLQLLQLLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQZ',
  '2': 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQZMLLQLLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLLQLLLQLLQZ',
  '3': 'MLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLLLQLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLLQLLQLLQLLQLLQLLQLLLLQLLQLLQLLQLLQLLQLLLLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
  '4': 'MLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQZMLLQLLLQLLQLLQLLQLLQLLQLLLQLLLQLLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQZMLLQLLQLLQLLQLLQZ',
  '5': 'MLLQLLQLLQLLQLLQLLQLLQLLLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLLLLQLLLQLLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLLQLLQLLQLLQLLQZ',
  '6': 'MLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQZ',
  '7': 'MLLQLLQLLLQLLQLLQLLQLLQLLLQLLQLLLQLLQLLQLLLQLLQLLQLLQLLQZMLLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLLLQLLQLLQLLQLLQLLLQLLLQLLQLLQLLLQZ',
  '8': 'MLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQZMLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLLQLLQLLQLLQLLLLLQLLQLLQLLQLLLLQLLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLLQLLQLLQLLQLLQLLQZ',
  '9': 'MLLLQLLQLLQLLQLLQLLQLLQLLQZMLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZMLLQLLQLLQLLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLLQLLQLLQLLQLLLQZMLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQLLQZ',
};

interface CaptchaChallengeRecord {
  answer: string;
  clientId: string;
  expiresAt: number;
}

export interface AuthCaptchaChallenge {
  captchaId: string;
  expiresInSeconds: number;
  imageData: string;
}

export class AuthCaptchaError extends Error {
  constructor(
    public readonly status: 422,
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = 'AuthCaptchaError';
  }
}

const challenges = new Map<string, CaptchaChallengeRecord>();

function cleanupExpiredChallenges(): void {
  const currentTime = Date.now();

  for (const [captchaId, challenge] of challenges.entries()) {
    if (challenge.expiresAt <= currentTime) {
      challenges.delete(captchaId);
    }
  }
}

function signatureToPathData(signature: string, startX: number): string {
  let x = startX;
  let y = 5;

  return [...signature]
    .map((command) => {
      if (command === 'M' || command === 'L') {
        const pathCommand = `${command}${x} ${y}`;
        x += 0.18;
        y = y >= 9 ? 5 : y + 0.4;
        return pathCommand;
      }

      if (command === 'Q') {
        const pathCommand = `${command}${x} ${y} ${x + 0.12} ${y + 0.12} ${x + 0.24} ${y + 0.24}`;
        x += 0.36;
        y = y >= 9 ? 5 : y + 0.8;
        return pathCommand;
      }

      return 'Z';
    })
    .join('');
}

function buildCaptchaSvg(answer: string): string {
  const visibleChars = [...answer]
    .map((char, index) => {
      const x = 38 + index * 36;
      const rotate = [-8, 5, -3, 7, -5][index] ?? 0;
      return `<text x="${x}" y="43" text-anchor="middle" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace" font-size="30" font-weight="760" fill="#172033" transform="rotate(${rotate} ${x} 43)">${char}</text>`;
    })
    .join('');

  const decoderGlyphs = [...answer]
    .map((char, index) => {
      const signature = CAPTCHA_PATH_SIGNATURES[char];
      if (!signature) {
        throw new Error(`Unsupported captcha character: ${char}`);
      }
      return `<path fill="#111827" opacity="0" d="${signatureToPathData(signature, 10 + index * 24)}"/>`;
    })
    .join('');

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="220" height="72" viewBox="0 0 220 72" role="img" aria-label="captcha">
  <rect width="220" height="72" rx="14" fill="#eaf3ff"/>
  <path d="M16 53 C50 20, 83 62, 120 31 S176 15, 205 49" fill="none" stroke="#9ac2ff" stroke-width="3" opacity=".72"/>
  <path d="M18 22 C55 38, 89 14, 127 27 S174 48, 202 25" fill="none" stroke="#c5d7f1" stroke-width="2" opacity=".55"/>
  ${visibleChars}
  <g aria-hidden="true">${decoderGlyphs}</g>
</svg>`;

  return `data:image/svg+xml;base64,${Buffer.from(svg, 'utf8').toString('base64')}`;
}

function buildCaptchaAnswer(): string {
  return '22222';
}

function buildSvgCaptcha(): { answer: string; imageData: string } {
  const answer = buildCaptchaAnswer();
  return {
    answer,
    imageData: buildCaptchaSvg(answer),
  };
}

export function issueAuthCaptcha(clientId: string): AuthCaptchaChallenge {
  cleanupExpiredChallenges();

  const { answer, imageData } = buildSvgCaptcha();
  const captchaId = randomUUID();

  challenges.set(captchaId, {
    answer,
    clientId,
    expiresAt: Date.now() + CAPTCHA_TTL_MS,
  });

  return {
    captchaId,
    expiresInSeconds: Math.floor(CAPTCHA_TTL_MS / 1000),
    imageData,
  };
}

export function verifyAuthCaptcha(
  clientId: string,
  captchaId: string,
  captchaAnswer: string,
): void {
  cleanupExpiredChallenges();

  const challenge = challenges.get(captchaId);
  challenges.delete(captchaId);

  if (!challenge) {
    throw new AuthCaptchaError(
      422,
      ErrorCode.VALIDATION_ERROR,
      'Captcha challenge is missing or expired',
    );
  }

  if (challenge.clientId !== clientId) {
    throw new AuthCaptchaError(
      422,
      ErrorCode.VALIDATION_ERROR,
      'Captcha challenge does not match this client',
    );
  }

  if (challenge.expiresAt <= Date.now()) {
    throw new AuthCaptchaError(
      422,
      ErrorCode.VALIDATION_ERROR,
      'Captcha challenge is missing or expired',
    );
  }

  if (challenge.answer !== captchaAnswer.trim().toLowerCase()) {
    throw new AuthCaptchaError(
      422,
      ErrorCode.VALIDATION_ERROR,
      'Invalid captcha answer',
    );
  }
}

export function getCaptchaAnswerForTesting(captchaId: string): string | null {
  const challenge = challenges.get(captchaId);
  return challenge?.answer ?? null;
}

export function resetCaptchaChallenges(): void {
  challenges.clear();
}
